[package]
name = "gmail_file_downloader"
version = "0.1.0"
edition = "2021"
authors = ["Your Name"]

[dependencies]
imap = "2.4.1"
native-tls = "0.2"
mailparse = "0.15.0"
dialoguer = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.19"